version: '3.9'

services:
  sftpgo:
    image: drakkan/sftpgo:latest
    container_name: sftpgo
    restart: always
    ports:
      - "3033:2022" # SFTP port
      - "9090:9090" # Admin web interface
    environment:
      - SFTPGO_HTTPD__BINDINGS__0__PORT=9090 # Port for the web interface
      - SFTPGO_HTTPD__BINDINGS__0__ENABLED=true
      - SFTPGO_LOG_LEVEL=info # Logging level (optional)
    volumes:
      - /mnt/c/123/sftp/data:/var/lib/sftpgo:rw # Persistent data storage
      - /mnt/c/123/sftp/config:/etc/sftpgo:rw   # Configuration files
      - /mnt/c/123/sftp/logs:/var/log/sftpgo:rw # Logs directory
