name: Publish Multiple Helm Charts to GitHub Pages

on:
  push:
    branches:
      - master  # Trigger the workflow when changes are pushed to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install Helm
      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: 'v3.12.0'  # You can specify a specific Helm version

      # Create a directory to store the packaged charts
      - name: Create charts directory
        run: mkdir -p ./charts

      # Find and package all Helm charts in the repository
      - name: Package all Helm charts
        run: |
          for chart in $(find . -name "Chart.yaml" -exec dirname {} \;); do
            helm package $chart --destination ./charts
          done

      # Update the index.yaml file for the Helm repository
      - name: Update Helm repo index
        run: |
          helm repo index ./charts --url https://ppts-ai.github.io/apps/

      # Push the packaged charts and index.yaml to GitHub Pages (gh-pages branch)
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./charts
          publish_branch: gh-pages
